In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a[:, 0]

array([1, 4])

In [9]:
b = np.array([i*i for i in range(10) if i%2==1])
c = b.tolist() # конвертирует массив обратно в список
c

[1, 9, 25, 49, 81]

In [10]:
a = np.zeros(100) # 100 элементный массив нулей, тип float
print(a)
b = np.zeros((2,8), int) # массив нулей размера 2×8 типа int
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [12]:
a = np.ones(10, int) # 10 элементный массив единиц типа int
b = np.pi * np.ones((5,5)) # хороший способ заполнить массив заданным значением
b

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [14]:
b.shape

(5, 5)

In [18]:
a = np.random.rand(5,5)
a

array([[0.85786027, 0.20396877, 0.82589536, 0.38194772, 0.42405208],
       [0.06640632, 0.3155153 , 0.34256731, 0.0124122 , 0.32154875],
       [0.70760059, 0.82516686, 0.27790129, 0.62473166, 0.20876962],
       [0.74618756, 0.7475935 , 0.34609939, 0.31088181, 0.07955234],
       [0.28778435, 0.22333718, 0.51538392, 0.56904232, 0.6182872 ]])

In [19]:
b = np.transpose(a) #можно транспонировать
b

array([[0.85786027, 0.06640632, 0.70760059, 0.74618756, 0.28778435],
       [0.20396877, 0.3155153 , 0.82516686, 0.7475935 , 0.22333718],
       [0.82589536, 0.34256731, 0.27790129, 0.34609939, 0.51538392],
       [0.38194772, 0.0124122 , 0.62473166, 0.31088181, 0.56904232],
       [0.42405208, 0.32154875, 0.20876962, 0.07955234, 0.6182872 ]])

In [20]:
np.matmul(a,b) #можно сделать матричное произведение

array([[1.78533487, 0.54534159, 1.33199211, 1.2309272 , 1.19761615],
       [0.54534159, 0.32485973, 0.47742572, 0.43342977, 0.47200322],
       [1.33199211, 0.47742572, 1.69270247, 1.45189943, 1.01573101],
       [1.2309272 , 0.43342977, 1.45189943, 1.33845277, 0.78617168],
       [1.19761615, 0.47200322, 1.01573101, 0.78617168, 1.10440814]])

In [21]:
# проверим, что матричное?
print(a)
print(np.eye(5))

[[0.85786027 0.20396877 0.82589536 0.38194772 0.42405208]
 [0.06640632 0.3155153  0.34256731 0.0124122  0.32154875]
 [0.70760059 0.82516686 0.27790129 0.62473166 0.20876962]
 [0.74618756 0.7475935  0.34609939 0.31088181 0.07955234]
 [0.28778435 0.22333718 0.51538392 0.56904232 0.6182872 ]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
np.matmul(a,np.eye(5)) #точно матричное, не верите?

array([[0.85786027, 0.20396877, 0.82589536, 0.38194772, 0.42405208],
       [0.06640632, 0.3155153 , 0.34256731, 0.0124122 , 0.32154875],
       [0.70760059, 0.82516686, 0.27790129, 0.62473166, 0.20876962],
       [0.74618756, 0.7475935 , 0.34609939, 0.31088181, 0.07955234],
       [0.28778435, 0.22333718, 0.51538392, 0.56904232, 0.6182872 ]])

In [37]:
# не путайте вектор, который транспонируется в такой же вектор!
a = np.ones(5)
print(a)
print(a.shape)

[1. 1. 1. 1. 1.]
(5,)


In [40]:
# и матрицу! Которая транспонируется как матрица!
a = np.ones((5,1))
print(a)
print(a.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [43]:
# одно можно превратить в другое
a = np.ones(5)
a_vect = a[:, np.newaxis]
print(a_vect)
print(a_vect.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [45]:
# numpy позволяет быстро фильтровать элементы массива
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# векторизация

In [24]:
def power(x,a):
    return x**a

vect_power = np.vectorize(power)

In [25]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
vect_power(x,5)

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

# broadcasting

In [58]:
a = np.ones((5,5))
print(a)
b = np.ones(5)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [57]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])