In [1]:
import numpy as np

In [23]:
a = np.ones((2,3), int)
a[0,0:2]

In [18]:
np.empty((2), dtype=int)

array([0, 0])

In [30]:
type(np.empty((2,3))[0,0])

array([[1., 5., 1.],
       [1., 1., 1.]])

In [21]:
l = [[1,2,3],[4,5,6]]
a = np.array(l)
a[:, 1]

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a[:, 0]

array([1, 4])

In [5]:
b = np.array([i*i for i in range(10) if i%2==1])
c = b.tolist() # конвертирует массив обратно в список
c

[1, 9, 25, 49, 81]

In [6]:
a = np.zeros(100) # 100 элементный массив нулей, тип float
print(a)
b = np.zeros((2,8), int) # массив нулей размера 2×8 типа int
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
a = np.ones(10, int) # 10 элементный массив единиц типа int
b = np.pi * np.ones((5,5)) # хороший способ заполнить массив заданным значением
b

In [7]:
b.shape

(2, 8)

In [8]:
a = np.random.rand(5,5)
a

array([[0.8034315 , 0.73062933, 0.19940353, 0.73685586, 0.56870681],
       [0.36802533, 0.82313472, 0.61766572, 0.39516561, 0.24820673],
       [0.26524543, 0.45925443, 0.29436153, 0.172195  , 0.43752444],
       [0.75116416, 0.00480156, 0.03129571, 0.13779562, 0.83046662],
       [0.48853137, 0.34087054, 0.76229609, 0.02568409, 0.79045292]])

In [ ]:
b = np.transpose(a) #можно транспонировать
b

In [ ]:
np.matmul(a,b) #можно сделать матричное произведение

In [ ]:
# проверим, что матричное?
print(a)
print(np.eye(5))

In [ ]:
np.matmul(a,np.eye(5)) #точно матричное, не верите?

In [ ]:
# не путайте вектор, который транспонируется в такой же вектор!
a = np.ones(5)
print(a)
print(a.shape)

In [ ]:
# и матрицу! Которая транспонируется как матрица!
a = np.ones((5,1))
print(a)
print(a.shape)

In [9]:
# одно можно превратить в другое
a = np.ones(5)
a_vect = a[:, np.newaxis]
print(a_vect)
print(a_vect.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [10]:
# вместе np.newaxis можно просто написать None - сработает так же
a = np.ones(5)
a_vect = a[:, None, None]
print(a_vect)
print(a_vect.shape)

[[[1.]]

 [[1.]]

 [[1.]]

 [[1.]]

 [[1.]]]
(5, 1, 1)


In [11]:
# numpy позволяет быстро фильтровать элементы массива
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# векторизация

In [13]:
def power(x,a):
    return x**a

vect_power = np.vectorize(power)

In [16]:
l = [1,2,3]
list(map(power, l))(2)

TypeError: power() missing 1 required positional argument: 'a'

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
vect_power(x,5)

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049])

# broadcasting

In [17]:
a = np.ones((5,5))
print(a)
b = np.ones(5)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [18]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])